name: flutter_metode_bayar
description: Plugin untuk melihat daftar metode pembayaran
version: 0.0.13
author: Anhar Tasman<anhar_tasman@yahoo.com>
homepage: https://bitbucket.org/anhartasman/flutter_metode_bayar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_bca.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_bni.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_bri.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_dana.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_gopay.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_link_aja.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_mandiri.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_ovo.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_permata.png
    - packages/flutter_metode_bayar/assets/icon_metode_bayar/icon_permata_bank.png
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
